---
# tasks file for apache

- name: Installing httpd (Apache)
  yum:
    name: httpd
    state: latest
  register: Output

- name: change httpd port using template j2
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: start service httpd - if install succeeded
  service:
    name: httpd
    state: started
  when: Output is succeeded
  notify:
  - restart apache
...
